- project:
    check:
      jobs: 
        - noop
        - testjob2
        
- job:
    name: testjob2
    run: playbooks/testjob2.yaml
    required-projects:
      - devops-zuul/anotherproject


        
