- job:
    name: testjob3
    run: playbooks/testjob3.yaml
    required-projects:
      - devops-zuul/anotherproject

- project:
    check:
      jobs:
        - testjob3
- project:
    check:
      jobs: 
        - noop
     
        
