- hosts: localhost
  tasks:
    - name: Unit test
      shell: |
             cd src
             ls
             echo "Runing unit test for add.py which is dynamic code getting 2 argument in command line"
             python ./playbooks/calculator.py
  
